import type { Apartment } from "~/types";

export const apartments: Apartment[] = [
    {
        id: 1,
        apartmentNumber: 104,
        image: "",
        title: "3-х комнатная квартира №104",
        area: 63.1,
        price: 6630500,
        rooms: 3,
        currentFloor: 1,
        totalFloors: 17,
    },
    {
        id: 2,
        apartmentNumber: 105,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №105",
        area: 55.3,
        price: 5810913,
        rooms: 2,
        currentFloor: 2,
        totalFloors: 17,
    },
    {
        id: 3,
        apartmentNumber: 106,
        image: "",
        title: "4-х комнатная квартира №106",
        area: 69.5,
        price: 7308407,
        rooms: 4,
        currentFloor: 3,
        totalFloors: 17,
    },
    {
        id: 4,
        apartmentNumber: 107,
        image: "/img/plan.webp",
        title: "3-х комнатная квартира №107",
        area: 60.0,
        price: 6305134,
        rooms: 3,
        currentFloor: 4,
        totalFloors: 17,
    },
    {
        id: 5,
        apartmentNumber: 108,
        image: "",
        title: "1-х комнатная квартира №108",
        area: 48.7,
        price: 5111160,
        rooms: 1,
        currentFloor: 5,
        totalFloors: 17,
    },
    {
        id: 6,
        apartmentNumber: 109,
        image: "/img/plan.webp",
        title: "3-х комнатная квартира №109",
        area: 65.0,
        price: 6830512,
        rooms: 3,
        currentFloor: 6,
        totalFloors: 17,
    },
    {
        id: 7,
        apartmentNumber: 110,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №110",
        area: 42.8,
        price: 4495656,
        rooms: 2,
        currentFloor: 7,
        totalFloors: 17,
    },
    {
        id: 8,
        apartmentNumber: 111,
        image: "/img/plan.webp",
        title: "3-х комнатная квартира №111",
        area: 38.4,
        price: 4035286,
        rooms: 3,
        currentFloor: 8,
        totalFloors: 17,
    },
    {
        id: 9,
        apartmentNumber: 112,
        image: "/img/plan.webp",
        title: "4-х комнатная квартира №112",
        area: 70.0,
        price: 7355990,
        rooms: 4,
        currentFloor: 9,
        totalFloors: 17,
    },
    {
        id: 10,
        apartmentNumber: 113,
        image: "/img/plan.webp",
        title: "1-х комнатная квартира №113",
        area: 33.2,
        price: 3488898,
        rooms: 1,
        currentFloor: 10,
        totalFloors: 17,
    },
    {
        id: 11,
        apartmentNumber: 114,
        image: "/img/plan.webp",
        title: "3-х комнатная квартира №114",
        area: 59.7,
        price: 6274578,
        rooms: 3,
        currentFloor: 11,
        totalFloors: 17,
    },
    {
        id: 12,
        apartmentNumber: 115,
        image: "",
        title: "2-х комнатная квартира №115",
        area: 51.4,
        price: 5400000,
        rooms: 2,
        currentFloor: 12,
        totalFloors: 17,
    },
    {
        id: 13,
        apartmentNumber: 116,
        image: "/img/plan.webp",
        title: "1-х комнатная квартира №116",
        area: 36.2,
        price: 3800000,
        rooms: 1,
        currentFloor: 13,
        totalFloors: 17,
    },
    {
        id: 14,
        apartmentNumber: 117,
        image: "",
        title: "4-х комнатная квартира №117",
        area: 72.3,
        price: 7600000,
        rooms: 4,
        currentFloor: 14,
        totalFloors: 17,
    },
    {
        id: 15,
        apartmentNumber: 118,
        image: "/img/plan.webp",
        title: "3-х комнатная квартира №118",
        area: 61.8,
        price: 6500000,
        rooms: 3,
        currentFloor: 15,
        totalFloors: 17,
    },
    {
        id: 16,
        apartmentNumber: 119,
        image: "",
        title: "2-х комнатная квартира №119",
        area: 47.5,
        price: 5000000,
        rooms: 2,
        currentFloor: 16,
        totalFloors: 17,
    },
    {
        id: 17,
        apartmentNumber: 120,
        image: "/img/plan.webp",
        title: "1-х комнатная квартира №120",
        area: 34.8,
        price: 3650000,
        rooms: 1,
        currentFloor: 17,
        totalFloors: 17,
    },
    {
        id: 18,
        apartmentNumber: 121,
        image: "",
        title: "3-х комнатная квартира №121",
        area: 66.2,
        price: 6900000,
        rooms: 3,
        currentFloor: 2,
        totalFloors: 17,
    },
    {
        id: 19,
        apartmentNumber: 122,
        image: "/img/plan.webp",
        title: "4-х комнатная квартира №122",
        area: 73.1,
        price: 7700000,
        rooms: 4,
        currentFloor: 5,
        totalFloors: 17,
    },
    {
        id: 20,
        apartmentNumber: 123,
        image: "",
        title: "2-х комнатная квартира №123",
        area: 50.0,
        price: 5250000,
        rooms: 2,
        currentFloor: 7,
        totalFloors: 17,
    },
    {
        id: 21,
        apartmentNumber: 124,
        image: "/img/plan.webp",
        title: "1-х комнатная квартира №124",
        area: 35.6,
        price: 3750000,
        rooms: 1,
        currentFloor: 9,
        totalFloors: 17,
    },
    {
        id: 22,
        apartmentNumber: 125,
        image: "",
        title: "3-х комнатная квартира №125",
        area: 64.5,
        price: 6750000,
        rooms: 3,
        currentFloor: 11,
        totalFloors: 17,
    },
    {
        id: 23,
        apartmentNumber: 126,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №126",
        area: 52.2,
        price: 5480000,
        rooms: 2,
        currentFloor: 13,
        totalFloors: 17,
    },
    {
        id: 24,
        apartmentNumber: 127,
        image: "",
        title: "4-х комнатная квартира №127",
        area: 71.0,
        price: 7450000,
        rooms: 4,
        currentFloor: 15,
        totalFloors: 17,
    },
    {
        id: 25,
        apartmentNumber: 128,
        image: "/img/plan.webp",
        title: "3-х комнатная квартира №128",
        area: 62.4,
        price: 6550000,
        rooms: 3,
        currentFloor: 16,
        totalFloors: 17,
    },
    {
        id: 26,
        apartmentNumber: 129,
        image: "",
        title: "1-х комнатная квартира №129",
        area: 37.2,
        price: 3900000,
        rooms: 1,
        currentFloor: 3,
        totalFloors: 17,
    },
    {
        id: 27,
        apartmentNumber: 130,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №130",
        area: 49.8,
        price: 5230000,
        rooms: 2,
        currentFloor: 6,
        totalFloors: 17,
    },
    {
        id: 28,
        apartmentNumber: 131,
        image: "",
        title: "3-х комнатная квартира №131",
        area: 67.0,
        price: 7000000,
        rooms: 3,
        currentFloor: 8,
        totalFloors: 17,
    },
    {
        id: 29,
        apartmentNumber: 132,
        image: "/img/plan.webp",
        title: "4-х комнатная квартира №132",
        area: 74.2,
        price: 7800000,
        rooms: 4,
        currentFloor: 10,
        totalFloors: 17,
    },
    {
        id: 30,
        apartmentNumber: 133,
        image: "",
        title: "2-х комнатная квартира №133",
        area: 46.7,
        price: 4950000,
        rooms: 2,
        currentFloor: 12,
        totalFloors: 17,
    },
    {
        id: 31,
        apartmentNumber: 134,
        image: "/img/plan.webp",
        title: "1-х комнатная квартира №134",
        area: 34.0,
        price: 3580000,
        rooms: 1,
        currentFloor: 14,
        totalFloors: 17,
    },
    {
        id: 32,
        apartmentNumber: 135,
        image: "",
        title: "3-х комнатная квартира №135",
        area: 63.8,
        price: 6680000,
        rooms: 3,
        currentFloor: 17,
        totalFloors: 17,
    },
    {
        id: 33,
        apartmentNumber: 136,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №136",
        area: 53.5,
        price: 5600000,
        rooms: 2,
        currentFloor: 4,
        totalFloors: 17,
    },
    {
        id: 34,
        apartmentNumber: 137,
        image: "",
        title: "4-х комнатная квартира №137",
        area: 72.8,
        price: 7650000,
        rooms: 4,
        currentFloor: 7,
        totalFloors: 17,
    },
    {
        id: 35,
        apartmentNumber: 138,
        image: "/img/plan.webp",
        title: "1-х комнатная квартира №138",
        area: 32.6,
        price: 3450000,
        rooms: 1,
        currentFloor: 9,
        totalFloors: 17,
    },
    {
        id: 36,
        apartmentNumber: 139,
        image: "",
        title: "3-х комнатная квартира №139",
        area: 60.9,
        price: 6420000,
        rooms: 3,
        currentFloor: 11,
        totalFloors: 17,
    },
    {
        id: 37,
        apartmentNumber: 140,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №140",
        area: 48.9,
        price: 5100000,
        rooms: 2,
        currentFloor: 13,
        totalFloors: 17,
    },
    {
        id: 38,
        apartmentNumber: 141,
        image: "",
        title: "4-х комнатная квартира №141",
        area: 75.0,
        price: 7900000,
        rooms: 4,
        currentFloor: 15,
        totalFloors: 17,
    },
    {
        id: 39,
        apartmentNumber: 142,
        image: "/img/plan.webp",
        title: "3-х комнатная квартира №142",
        area: 62.9,
        price: 6590000,
        rooms: 3,
        currentFloor: 2,
        totalFloors: 17,
    },
    {
        id: 40,
        apartmentNumber: 143,
        image: "",
        title: "1-х комнатная квартира №143",
        area: 36.0,
        price: 3780000,
        rooms: 1,
        currentFloor: 5,
        totalFloors: 17,
    },
    {
        id: 41,
        apartmentNumber: 144,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №144",
        area: 54.2,
        price: 5670000,
        rooms: 2,
        currentFloor: 8,
        totalFloors: 17,
    },
    {
        id: 42,
        apartmentNumber: 145,
        image: "",
        title: "3-х комнатная квартира №145",
        area: 65.7,
        price: 6900000,
        rooms: 3,
        currentFloor: 10,
        totalFloors: 17,
    },
    {
        id: 43,
        apartmentNumber: 146,
        image: "/img/plan.webp",
        title: "4-х комнатная квартира №146",
        area: 76.4,
        price: 8050000,
        rooms: 4,
        currentFloor: 12,
        totalFloors: 17,
    },
    {
        id: 44,
        apartmentNumber: 147,
        image: "",
        title: "1-х комнатная квартира №147",
        area: 33.8,
        price: 3550000,
        rooms: 1,
        currentFloor: 14,
        totalFloors: 17,
    },
    {
        id: 45,
        apartmentNumber: 148,
        image: "/img/plan.webp",
        title: "2-х комнатная квартира №148",
        area: 50.6,
        price: 5320000,
        rooms: 2,
        currentFloor: 16,
        totalFloors: 17,
    },
    {
        id: 46,
        apartmentNumber: 149,
        image: "",
        title: "3-х комнатная квартира №149",
        area: 64.0,
        price: 6720000,
        rooms: 3,
        currentFloor: 17,
        totalFloors: 17,
    },
];
